services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    command:
      - start-dev
    ports:
      - "28080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

##comando para subir docker compose up -d